### ISSUE TITLE
Redmine 4.0 compability

### ISSUE THREAD

**Issue by crunchtime-ali** [tf/redmine_merge_request_links#11]
Dear @tf,
did you test whether the plugin is still compatible with Redmine 4.0?

**Comment by tf** [comment]
I changed the Travis config to also run the test suite against the Redmine 4 tag of the official Redmine issue (see #12). A few minor changes to the test suite were required, but now that works. I haven't tried it manually, though, so far. So if you have a staging system where you can give it a go, I'd be happy to get you feedback.

**Comment by tf** [comment]
Any update?

**Comment by tf** [comment]
Looks like people are using the plugin with Redmine 4.
