### ISSUE TITLE
Error after executing git apply command

### ISSUE THREAD

**Issue by Tjird** [tf/redmine_merge_request_links#13]
This is the error that I get when executing the git apply command. 

```
root@redmine-dev-server-1:/usr/src/redmine# git apply plugins/redmine_merge_request_links/patches/view_hook_issues_show_after_details.patch
error: patch failed: app/views/issues/show.html.erb:118
error: app/views/issues/show.html.erb: patch does not apply
```

The ENV is set and the redmine version is 3.4.6. 

These are the lines around line 118 in show.html.erb

```
<% if @relations.present? || User.current.allowed_to?(:manage_issue_relations, @project) %>
<hr />
<div id="relations">
<%= render :partial => 'relations' %>
</div>
<% end %>
</div>     <---- this is line 118
<%= call_hook(:view_issues_show_after_details, :issue => @issue) %>
```

**Comment by tf** [comment]
For me, applying the patch to Redmine 3.4.6 works. Looking at `app/views/issues/show.html.erb` at that version

https://github.com/redmine/redmine/blob/06f88b4979fe51df09d4d8d27daece4f9b620f28/app/views/issues/show.html.erb#L118

line 118 appears to be an empty line. So maybe the file changed locally on your system?

**Comment by Tjird** [comment]
Strange but ok. I know use the Dockerfile from you and it started but the merge_requests/event page is not found.

**Comment by tf** [comment]
The patch is [applied in CI](https://github.com/tf/redmine_merge_request_links/blob/67fbeda233604fb7cabbae37da71c71c8fb9d88e/Dockerfile#L5) for both [Redmine 3.4 and 4.0](https://github.com/tf/redmine_merge_request_links/blob/67fbeda233604fb7cabbae37da71c71c8fb9d88e/.travis.yml#L4-L5). I also just tried it again on my local machine and could not reproduce the error.

If you can't find out why it fails on your machine you can always apply the patch manually. It is just one line.

**Comment by Tjird** [comment]
Allright, then I need to apply is manually. But then it's the question what do I need to do?
I don't understand what the patch file does.

**Comment by tf** [comment]
The patch inserts the following line:

```
<%= call_hook(:view_issues_show_after_details, :issue => @issue) %>
```
[here](https://github.com/redmine/redmine/blob/765274986c26af38ca49aab83dfff57efb055bd9/app/views/issues/show.html.erb#L122) in `app/views/issues/show.html.erb`.

**Comment by Tjird** [comment]
Nice.. The funniest part is that this line already is in the file. I don't know what to do next x).

**Comment by tf** [comment]
Sorry. This is not a support forum. The issue tracker is meant for discussing bugs and feature enhancements. Please refer to the Redmine docs on how to install plugins.
