### ISSUE TITLE
Patch fails for Redmine 3.4.11

### ISSUE THREAD

**Issue by tofi86** [tf/redmine_merge_request_links#14]
Hi, I'm using Redmine 3.4.11 and ypur plugin v2.1.1 but after updating from 3.4.10 to 3.4.11 the patch fails:

```
/var/www/redmine# git apply plugins/redmine_merge_request_links/patches/view_hook_issues_show_after_details.patch
error: patch failed: app/views/issues/show.html.erb:118
error: app/views/issues/show.html.erb: patch does not apply
```

Can you provide an updated patch please?

Thanks for this great plugin!

Best, Tobias

**Comment by tf** [comment]
The patch still works for me in Redmine 3.4.11. It fails, though, in Redmine 4.0.4 (see [Travis build](https://travis-ci.org/tf/redmine_merge_request_links/builds/498659467)). I've added a new patch that works with Redmine 4.0.4 in #15.

**Comment by tofi86** [comment]
Sorry, totally my fault 🙈  I was blind and already had it applied... 🙄
