### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by saitho** [tf/redmine_merge_request_links#16]
[Gitea](https://github.com/go-gitea/gitea) is an open source version control system and supports web hooks similarly to GitHub.

I think integrating it should be easy. I'll take a look at that.

Haven't used this plugin yet. I'd adjust two files:
* add environment variable in `/lib/redmine_merge_request_links.rb`
* add file for Gitea in `lib/redmine_merge_request_links/event_handlers`

It that everything I'd have to do? :)

**Comment by tf** [comment]
This sounds fine. Please also add [some specs](https://github.com/tf/redmine_merge_request_links/blob/master/test/functional/merge_requests_controller_test.rb) with example payloads for Gitea webhooks and update the README.
