### ISSUE TITLE
Hook executed successfully but returned HTTP 403

### ISSUE THREAD

**Issue by lakostin** [tf/redmine_merge_request_links#21]
Started POST "/merge_requests/event" for 127.0.0.1 at 2019-12-13 18:50:01 +0300
Processing by MergeRequestsController#event as HTML
.....
Current user: anonymous
Completed 403 Forbidden in 1ms (ActiveRecord: 0.3ms)

**Comment by lakostin** [comment]
> `REDMINE_MERGE_REQUEST_LINKS_GITLAB_WEBHOOK_TOKEN`/`REDMINE_MERGE_REQUEST_LINKS_GITHUB_WEBHOOK_TOKEN` set correctly?

Yep

**Comment by lakostin** [comment]
> `REDMINE_MERGE_REQUEST_LINKS_GITLAB_WEBHOOK_TOKEN`/`REDMINE_MERGE_REQUEST_LINKS_GITHUB_WEBHOOK_TOKEN` set correctly?

Yep

**Comment by tf** [comment]
I guess the 403 comes from [this line](https://github.com/tf/redmine_merge_request_links/blob/c101e6ae2894d977307702ae86167bf0467281d6/app/controllers/merge_requests_controller.rb#L8). You will have to debug why the verification fails in your setup.

**Comment by lakostin** [comment]
How to debug it?

**Comment by lakostin** [comment]
Is it ok, that the user is anonymous?

**Comment by tf** [comment]
Yes. The token verification replaces user authentication. 

We should probably add some logging for these cases. The problem is that currently the token verification is implemented in each service specific event handler separately (e.g. [GitHub even handler](https://github.com/tf/redmine_merge_request_links/blob/c101e6ae2894d977307702ae86167bf0467281d6/lib/redmine_merge_request_links/event_handlers/github.rb#L12)). So code that distinguishes between cases "token not configured"/"signature does not match" and logs warnings would need to be duplicated. I think it would be a good idea to extract some of this logic into a shared method that then passes the token to the event handler explicitly.

For your case, though, you could temporarily add some `Rails.logger.info` calls to the event handler of the service you are interested in your local copy of the plugin.

**Comment by lakostin** [comment]
I added 
Rails.logger.info(request)
Rails.logger.info(event_handler.verify(request))

and here is the result.

Current user: anonymous
#<ActionDispatch::Request:0x00005599e067d278>
false
Completed 403 Forbidden in 1ms

Not clear what to do with it...

**Comment by tf** [comment]
Add something like

```
Rails.logger.info("Token: #{@token}")
Rails.logger.info(request.headers['X-Hub-Signature'])
```
to the top of [`Redmine_mergeRequestLinks::EventHandlers::Github#verify`](https://github.com/tf/redmine_merge_request_links/blob/c101e6ae2894d977307702ae86167bf0467281d6/lib/redmine_merge_request_links/event_handlers/github.rb#L12)

or 

```
Rails.logger.info("Token: #{@token}")
Rails.logger.info(request.headers['X-Gitlab-Token'])
```

to the top of [`Redmine_mergeRequestLinks::EventHandlers::Github#verify`](https://github.com/tf/redmine_merge_request_links/blob/c101e6ae2894d977307702ae86167bf0467281d6/lib/redmine_merge_request_links/event_handlers/gitlab.rb#L14.)

**Comment by lakostin** [comment]
def verify(request)
  Rails.logger.info("xoxo")
  Rails.logger.info("Token: #{@token}")
  Rails.logger.info("xoxo")
  Rails.logger.info(request.headers['X-Gitlab-Token'])
  request.headers['X-Gitlab-Token'] == @token
end

And here is the result...
xoxo
Token:
xoxo
hDHjcQPpW44K5bHMidYO
xoxo
false
xoxo
Token:
xoxo
hDHjcQPpW44K5bHMidYO
xoxo

**Comment by tf** [comment]
So as I suspected initially, the `REDMINE_MERGE_REQUEST_LINKS_*_WEBHOOK_TOKEN` variables are not set.

The `@token` you logged is read from the environment [here](https://github.com/tf/redmine_merge_request_links/blob/c101e6ae2894d977307702ae86167bf0467281d6/lib/redmine_merge_request_links.rb#L4). So the fact that it is empty, means that the environment variable is not set for you webserver process.

**Comment by lakostin** [comment]
env variables are set but app still can't see it...
ruby -e 'p ENV["REDMINE_MERGE_REQUEST_LINKS_GITLAB_WEBHOOK_TOKEN"]'
"hDHjcQPpW44K5bHMidYO"

Anyway i can set it manually.

But here is another problem. Migration is not completed. Should i also do something to fix it?
ActiveRecord::StatementInvalid (Mysql2::Error: Table 'easy.merge_requests' doesn't exist: SHOW FULL FIELDS FROM `merge_requests`):

**Comment by tf** [comment]
Did you run `rake redmine:plugins:migrate RAILS_ENV=production` like is says in the readme?

**Comment by lakostin** [comment]
After complete reinstall hook started to work finally :)
but now the link is not appeared in the issue.
is this plugin compatible with easy redmine?

**Comment by tf** [comment]
It sounds like you did not apply the Git patch for the Redmine source code which adds the hook to render the box.

Have you read the readme? I'm happy to help, but I find it a bit exhausting to walk you through each step here when everything I say is written in the readme.

Regarding Easy Redmine: I never used it. If the view patch applies then I guess it should work.

**Comment by lakostin** [comment]
I know, sorry. I read the readme carefully multiple times but it doesnt work just out of the box...
To make it work each step should be debugged...

**Comment by lakostin** [comment]
patch was applied successfully btw

**Comment by tf** [comment]
No problem. I'm also happy to accept PRs that improve the readme or cover more edge cases. So it works now?

**Comment by lakostin** [comment]
no, hook works, mr table contains rows, patch is applied, but the link is not shown.
i set "View associated merge requests" for all roles.
Merge request links is enabled for the project.
maybe you can send a screenshot so at least i know where to search for this link?

**Comment by tf** [comment]
It should display a box next to the journal items on the issue show page

![image](https://user-images.githubusercontent.com/26554/71083059-75971980-2192-11ea-9604-6f62ce747eb0.png)

**Comment by lakostin** [comment]
maybe you can help with debugging this case as well :)

**Comment by lakostin** [comment]
it now works finally!! easy redmine moved all pages to another place and kept all old pages. So the patch applied, but these changes actually were not displayed.
Thank you very much for help!
I think i should keep my own fork for easy redmine so the plugin could work correctly.

**Comment by tf** [comment]
Happy to hear that! :tada: 

It'd be great if you could open a PR that adds a hint to the readme where the change of the patch needs to applied in the Easy Redmine case.

**Comment by lakostin** [comment]
ok.
and environment variable was not applied because systemd hadn't seen it so it should be set in .service file.

**Comment by tf** [comment]
> and environment variable was not applied because systemd hadn't seen it so it should be set in .service file.

This sounds like something specific to your deployment setup, though.
